name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  VCPKG_COMMIT: af2287382b1991dbdcb7e5112d236f3323b9dd7a
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}\vcpkg\binary-cache

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ env.VCPKG_COMMIT }}-v1

      - uses: actions/checkout@v3
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        with:
          repository: Microsoft/vcpkg
          path: vcpkg
          ref: ${{ env.VCPKG_COMMIT }}

      - name: Install vcpkg dependencies
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/vcpkg
        run: |
          echo $Env:VCPKG_DEFAULT_BINARY_CACHE
          mkdir $Env:VCPKG_DEFAULT_BINARY_CACHE
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install sdl2:x64-windows

      - uses: actions/checkout@v3
        with:
          repository: agate-lang/gamma
          submodules: recursive
          path: gamma

      - name: Configure
        shell: cmd
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -S ${{ github.workspace }}/gamma -B ${{ github.workspace }}/gamma/build

      - name: Build
        shell: cmd
        run: |
          cmake --build ${{ github.workspace }}/gamma/build --config ${{ env.BUILD_TYPE }} --parallel
